"""
Django settings for DjangoTecnisuelos project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


    
from pathlib import Path
import os
from reportlab.pdfgen import canvas
import pymysql
pymysql.install_as_MySQLdb()
from . import db as db


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-npe4uaf6bkpf1!^oit6p5r_43+l0cyt%%fan_h3igaliku#y@('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'import_export',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
   
]



JAZZMIN_SETTINGS = {
    "search_model": ["auth.User", "auth.Group"],
    "site_title": "Tecnisuelos Admin",
    "site_header": "Tecnisuelos",
    "site_brand": "Tecnisuelos",
    "site_logo": "imagenes/logo2.png",  
    "site_icon": None,  
    "welcome_sign": "Bienvenido a TecniSuelos",
    "custom_css": None, 
    "copyright": "© 2023 Tecnisuelos",
    "button_rounded": True,
    "vertical_tabs" : True,
    
    "icons": {
        #User
        "auth.Group": "fas fa-users",
        "auth.user": "fas fa-solid fa-user-tie",  
        #Client
        "core.Client" : "fas fa-solid fa-user",
        "core.LegalClient" : "fas fa-light fa-user-tie",
        #Inventory
        "core.Category" : "fas fa-solid fa-layer-group",
        "core.Inventory" : "fas fa-solid fa-clipboard",
        #FielTrial
        "core.FielTrial" : "fas fa-solid fa-hammer",
        "core.Engineer" : "fas fa-light fa-user-check",
        "core.Escarificacion": "fas fa-light fa-map",
        "core.SoilAnalysis" : "fas fa-light fa-chart-bar",
        "core.SoilCompactionTest" : "fas fa-light fa-window-restore",
        #LaboratoryTrial
        "core.LaboratoryTrial" : "fas fa-solid fa-flask",
        "core.LaboratoryWorker" : "fas fa-light fa-user-check",
        "core.ResistanceTest" : "fas fa-light fa-vials",
        "core.PetrographicAnalysis" : "fas fa-light fa-chart-line",    
        "core.TestPermeability" : "fas fa-light fa-microscope",   
        
        
        
        
    },
    "show_ui_builder": True,

}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-navy",
    "navbar": "navbar-gray-dark navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-lightblue",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "journal",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-info",
        "secondary": "btn-outline-info",
        "info": "btn-info",
        "warning": "btn-info",
        "danger": "btn-outline-info",
        "success": "btn-outline-info"
    },
    "actions_sticky_top": True
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



# Media files
MEDIA_URL = 'media/'
MEDIAFILES_DIRS = (
    os.path.join(BASE_DIR,'media'),
)

ROOT_URLCONF = 'DjangoTecnisuelos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoTecnisuelos.wsgi.application'


# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tecnidjango',
        'USER': 'root',
        'PASSWORD': 'root1234',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True 
# EMAIL_HOST_USER = 'tecnisuelos24@gmail.com'
# EMAIL_HOST_PASSWORD = 'cxlj ljcr bqwq cwbj'
# EMAIL_SSL_CA_FILE = '/usr/local/share/ncat/ca-bundle.crt'

EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = '25e972b04f0dae'
EMAIL_HOST_PASSWORD = '5f0f2b6717e3ab'
EMAIL_PORT = '2525'

# Configuración de manejo de errores del servidor 500
SERVER_ERROR = 'DjangoTecnisuelos.views.error500'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

LOGOUT_REDIRECT_URL = '/logout/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

